#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: This API supports OAuth security
describedBy:
  headers:
    phoneNumber:
      description: please use a valid ClientID and ClientSecret
      required: false
  queryParameters:
    ClientID:
      type: string
      required: true
    ClientSecret:
      type: string
      required: true
  responses:
    200:
      description: OK
    401:
      description: Unauthorized
    403:
      description: Forbidden